export const SOFIFA_PROVIDER = "sofifa";

export const MVP_FIELDS = {
  nations: ["sofifaId", "name", "iso2", "iso3"],
  leagues: ["sofifaId", "name", "shortName", "countrySofifaId", "level", "gender"],
  clubs: [
    "sofifaId",
    "name",
    "shortName",
    "countrySofifaId",
    "leagueSofifaId",
    "city",
    "foundedYear",
    "stadiumName",
  ],
  players: [
    "sofifaId",
    "fullName",
    "knownAs",
    "age",
    "dateOfBirth",
    "nationalitySofifaId",
    "clubSofifaId",
    "leagueSofifaId",
    "primaryPosition",
    "positions",
    "overall",
    "potential",
    "preferredFoot",
    "heightCm",
    "valueAmount",
    "wageAmount",
    "currency",
    "attributes",
  ],
};

export const VALID_POSITIONS = new Set([
  "GK",
  "RWB",
  "RB",
  "RCB",
  "CB",
  "LCB",
  "LB",
  "LWB",
  "RDM",
  "CDM",
  "LDM",
  "RM",
  "RCM",
  "CM",
  "LCM",
  "LM",
  "RAM",
  "CAM",
  "LAM",
  "RW",
  "RF",
  "CF",
  "LF",
  "LW",
  "RS",
  "ST",
  "LS",
]);

export const RATING_FIELDS = new Set([
  "overall",
  "potential",
  "crossing",
  "finishing",
  "headingAccuracy",
  "shortPassing",
  "volleys",
  "dribbling",
  "curve",
  "freeKickAccuracy",
  "longPassing",
  "ballControl",
  "acceleration",
  "sprintSpeed",
  "agility",
  "reactions",
  "balance",
  "shotPower",
  "jumping",
  "stamina",
  "strength",
  "longShots",
  "aggression",
  "interceptions",
  "positioning",
  "vision",
  "penalties",
  "composure",
  "defensiveAwareness",
  "standingTackle",
  "slidingTackle",
  "gkDiving",
  "gkHandling",
  "gkKicking",
  "gkPositioning",
  "gkReflexes",
]);
